version: '3.8'

services:
  # Backend API service
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: melody-transcriber-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/melody-transcriber
      - JWT_SECRET=your_jwt_secret_key_change_this_in_production
    depends_on:
      - mongo
    networks:
      - melody-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: melody-transcriber-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    networks:
      - melody-network

  # MongoDB service
  mongo:
    image: mongo:6-jammy
    container_name: melody-transcriber-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - melody-network

volumes:
  mongo-data:

networks:
  melody-network:
    driver: bridge